name: CI/CD Pipeline for Maya CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f "setup.py" ] || [ -f "pyproject.toml" ]; then
            pip install -e .
          fi
          pip install pytest

      - name: Verify Tests Directory Exists
        run: |
          if [ ! -d "tests" ]; then
            echo "❌ ERROR: 'tests/' directory not found!"
            exit 1
          fi

      - name: Run Tests
        run: pytest tests/ --maxfail=5 --disable-warnings

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install build dependencies
        run: pip install setuptools wheel build

      - name: Verify Packaging Files Exist
        run: |
          if [ ! -f "setup.py" ] && [ ! -f "pyproject.toml" ]; then
            echo "❌ ERROR: Neither 'setup.py' nor 'pyproject.toml' found!"
            exit 1
          fi

      - name: Build Distribution Files
        run: python -m build

      - name: Upload Package as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: maya-cli-package
          path: dist/*

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Twine
        run: pip install twine

      - name: Download Package Artifact
        uses: actions/download-artifact@v3
        with:
          name: maya-cli-package
          path: dist

      - name: Verify Package Files
        run: |
          if [ ! -f "dist/*.tar.gz" ] && [ ! -f "dist/*.whl" ]; then
            echo "❌ ERROR: No package files found in 'dist/'"
            exit 1
          fi

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
